### ISSUE TITLE
game inhoud

### ISSUE THREAD

**Issue by JuliaSuijker** [emmaus-4v/game-in1-julia#1]
@vangeest (Is dit hoe ik ervoor zorg dat u een mailtje krijgt?)
Mijn game is gebaseerd op een soort visual storytelling. Het is daarom niet gebaseerd op vijanden aanvallen, maar eerder gewoon op het verhaal te volgen. Hierdoor maakt mijn spel geen gebruik van vijanden, maar eerder gewoon van andere karakters. Ook kan je hier geen punten scoren of mensen  aanvallen. Ik wil eerder een soort dialoog pop up maken waar de speler keuze krijgt tussen 2 dialoogopties die allebei een andere reactie krijgen. Zou dit voldoende zijn? Ik weer namelijk niet of dit exact de bedoeling is.

**Comment by vangeest** [comment]
Julia, het is prima als jouw game andere karakters in plaats van vijanden gebruikt. Het template mag (moet) je dan aanpassen.
